### ISSUE TITLE
Does not seem to work on 1.16.4

### ISSUE THREAD

**Issue by gymnae** [adriantodt/TotallyBalancedFallFlying#1]
Installed it on my server, but seems to have no effect on clients. Would they need to install the mod, or is it server sided?

**Comment by NotJustAnna** [comment]
They do need to install the mod

**Comment by gymnae** [comment]
Ah, thanks Adrian, so I guess this won't work as server side only then to enable elytra flight for everyone.
I will close this issue then.

**Comment by NotJustAnna** [comment]
I wanted to make this mod server-side only if possible but elytra flight requires client/server coordination.
